### ISSUE TITLE
Login in python2.7

### ISSUE THREAD

**Issue by mbulla** [MickaelRigault/ztfquery#5]
Hi Michael,
login does not seem to be working in python2.7. I get the following error:

/Users/mattia/anaconda/lib/python2.7/site-packages/ztfquery/__init__.py in <module>()
      5 from .io import has_encryption, set_account
      6 if not has_encryption():
----> 7     set_account("irsa")

/Users/mattia/anaconda/lib/python2.7/site-packages/ztfquery/io.pyc in set_account(which, username, password)
     76     if password is None: password = getpass.getpass()
     77     password_ = base64.b64encode( password.encode("utf-8") )
---> 78     config[which.lower()] = {"username":username, "password": password_ }
     79     with open( _ENCRYPT_FILE , 'w') as configfile:
     80         config.write(configfile)

AttributeError: ConfigParser instance has no attribute '__setitem__'

Mattia

**Comment by MickaelRigault** [comment]
Hi Mattia, 
I'll look into this, but you have to migrate to python 3+ because a lot of packages, including astropy will soon not be 2.7 compatible.

**Comment by MickaelRigault** [comment]
can you git pull and reinstall and test ?
For that, make sure that you do not have a ~/.ztfquery file (if so rm it), just to make sure you start back from strach.

Then set your account values.
then do:
```python
from ztfquery import io
io._load_id_("irsa")
```

Tell me if it works and if you logins are correct.

**Comment by mbulla** [comment]
Hi Mickael, thanks!

Then don't worry about it. I was planning to migrate to python 3 at some point anyway. Better doing that now ;-)

Thanks!
Mattia

On Aug 20, 2018 18:12, Mickael Rigault <notifications@github.com> wrote:

Hi Mattia,
I'll look into this, but you have to migrate to python 3+ because a lot of packages, including astropy will soon not be 2.7 compatible.

**Comment by mbulla** [comment]
Thanks Mickael. I got the following error now:

---------------------------------------------------------------------------
NoSectionError                            Traceback (most recent call last)
<ipython-input-2-f5c8397fd139> in <module>()
----> 1 from ztfquery import io
      2 io._load_id_("irsa")

/Users/mattia/anaconda/envs/py36/lib/python3.5/site-packages/ztfquery/ztfquery/__init__.py in <module>()
      5 from .io import has_encryption, set_account
      6 if not has_encryption():
----> 7     set_account("irsa")

/Users/mattia/anaconda/envs/py36/lib/python3.5/site-packages/ztfquery/ztfquery/io.pyc in set_account(which, username, password)
     83         config[which.lower()] = {"username":username, "password": password_ }
     84     else:
---> 85         config.set(which.lower(),"username",username)
     86         config.set(which.lower(),"password",password_)
     87 

/Users/mattia/anaconda/lib/python2.7/ConfigParser.pyc in set(self, section, option, value)
    394                 sectdict = self._sections[section]
    395             except KeyError:
--> 396                 raise NoSectionError(section)
    397         sectdict[self.optionxform(option)] = value
    398 

NoSectionError: No section: 'irsa'
